name: Sync Repository

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
        
    - name: Sync to Target Repository
      env:
        TARGET_REPO: "git@github.com:Mixhi1845/companion-vercel.git"
      run: |
        git remote add target $TARGET_REPO
        git push --force --prune target HEAD:master
        
    - name: Clean up
      if: always()
      run: |
        rm -f $HOME/.ssh/id_rsa